package my.prct.gradle;

import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@RestController
public class DemoController {
  public boolean someLibraryMethod() {
    return true;
  }

  public boolean oneMethodReturnFalse() {
    return false;
  }

  //    @RequestMapping("/greeting")
  @RequestMapping(path = "/")
  public String greeting(@RequestParam(value = "name", required = false, defaultValue = "world") String name,
      Model model) {

    model.addAttribute("name", name);
    return "greeting";
  }

}
