package my.prct.gradle;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;


import static org.junit.Assert.*;

public class DemoControllerTest {
    @Test
    public void testSomeLibraryMethod() {
        DemoController classUnderTest = new DemoController();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

        //assertFalse("test false 1", classUnderTest.someLibraryMethod());

    }
    
    @Test
    public void test2(){
    	DemoController library = new DemoController();
    	assertFalse("test false 2", library.oneMethodReturnFalse());

    }

}
