package my.prct.gradle;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;


import static org.junit.Assert.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        
        //assertFalse("test false 1", classUnderTest.someLibraryMethod());
        
    }
    
    @Test
    public void test2(){
    	Library library = new Library();
    	assertFalse("test false 2", library.someLibraryMethod());
    	
    }
    
}
