package com.vt.demo.controller;

import java.util.concurrent.atomic.AtomicLong;

import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.vt.demo.bean.User;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@RestController
public class DemoController {
	
	private static final String template = "Hello, %s!";
	
	private final AtomicLong counter = new AtomicLong();

	public boolean someLibraryMethod() {
		return true;
	}

	public boolean oneMethodReturnFalse() {
		return false;
	}

	@RequestMapping(path = "/")
	public String greeting(Model model) {

		return "greeting";
	}
	
	@RequestMapping(path="/user" , method=RequestMethod.GET)
    public User greeting(@RequestParam(value="name", defaultValue="zhangsan") String name) {
        return new User(counter.incrementAndGet(),
                            String.format(template, name));
    }

}
